# Generated by Django 4.2 on 2025-09-05 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_menu_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='desired_table',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='time',
            field=models.IntegerField(default=120),
        ),
    ]
